document.writeln("<div class='right_swt_pc'>");
document.writeln("	<div class='right_swt_pc_tab'>");
document.writeln("		<ul>");
document.writeln("			<li class='f-icon f-chat'>");
document.writeln("				<a onclick='openZoosUrl();return false;' href='javascript:;' id='sidebar-chat'><span>online chat</span></a>");
document.writeln("			</li>");
document.writeln("			<li class='f-icon f-whatsapp'>");
document.writeln("				<a id='whatsapp_pc' target='_blank' rel='nofollow' href='https://api.whatsapp.com/send?phone=8618151000009&text=Hi, JOBY, How are you? I am pretty interested in your products, could i know more about your products.&data&lang=en' ><span>WhatsApp</span></a>");
document.writeln("				<div class='msgbox'><p>WhatsApp</p></div>");
document.writeln("			</li>");
document.writeln("			<li class='f-icon f-facebook'>");
document.writeln("				<a href='//www.facebook.com/JOBYAOGRAND/?ref=bookmarks' target='_blank' rel='nofollow'><span>facebook</span></a>");
document.writeln("				<div class='msgbox'><p>Facebook</p></div>");
document.writeln("			</li>");
document.writeln("			<li class='f-icon f-linkedin'>");
document.writeln("				<a href=\"//www.linkedin.com/company/aogrand-int'l-corp/?viewAsMember=true\" target='_blank' rel='nofollow'><span>Linkedin</span></a>");
document.writeln("				<div class='msgbox'><p>Linkedin</p></div>");
document.writeln("			</li>");
document.writeln("			<li class='f-icon f-youtube'>");
document.writeln("				<a href='//www.youtube.com/channel/UCJR23HjBAxM9EIvVS7t2YVg?view_as=subscriber' target='_blank' rel='nofollow'><span>YouTube</span></a>");
document.writeln("				<div class='msgbox'><p>YouTube</p></div>");
document.writeln("			</li>");
document.writeln("			<li class='f-icon f-twitter'>");
document.writeln("				<a href='//twitter.com/ao_grand' target='_blank' rel='nofollow'><span>Twitter</span></a>");
document.writeln("				<div class='msgbox'><p>Twitter</p></div>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("<div class='right_swt_wap'>");
document.writeln("	<div class='f-swt'>");
document.writeln("		<ul>");
document.writeln("			<li id='chatonline'>");
document.writeln("				<a onclick='reportCustomEvent_chat();openZoosUrl();return false;' href='javascript:;'><span>Chat online</span></a>");
document.writeln("			</li>");
document.writeln("			<li id='callus'>");
document.writeln("				<a id='whatsapp_wap' target='_blank' rel='nofollow' href='https://api.whatsapp.com/send?phone=8618151000009&text=Hi, JOBY, How are you? I am pretty interested in your products, could i know more about your products.&data&lang=en' ><span>WhatsApp</span></a>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("*{margin: 0;padding: 0;}a{ text-decoration: none;}li{list-style: none;}");
document.writeln("	.right_swt_pc{width: 40px;position: fixed;right: 0;top: 25%;background: #FFFFFF;z-index:999999;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li{position: relative;width: 40px;text-align: center;cursor: pointer;border-bottom: 1px solid #e5e5e5; height: 54px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li a{display: inline-block;height: 100%;line-height: 999;overflow: hidden;}	");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-chat{height: 80px;background: url(/skin/jobyhome/img/right_swt/f-ico_line.jpg) center no-repeat;background-size: 40px 80px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-whatsapp{background: url(/skin/jobyhome/img/right_swt/f-ico6.png) no-repeat center;background-size: 30px 30px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-whatsapp:hover{background: url(/skin/jobyhome/img/right_swt/f-ico6-6.png) #009b4c no-repeat center;background-size: 30px 30px;}");		
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-facebook{background: url(/skin/jobyhome/img/right_swt/f-ico1.png) no-repeat center;background-size: 30px 30px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-facebook:hover{background: url(/skin/jobyhome/img/right_swt/f-ico1-1.png) #009b4c no-repeat center;background-size: 30px 30px}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-linkedin{background: url(/skin/jobyhome/img/right_swt/f-ico2.png) no-repeat center;background-size: 30px 30px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-linkedin:hover{background: url(/skin/jobyhome/img/right_swt/f-ico2-2.png) #009b4c no-repeat center;background-size: 30px 30px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-youtube{background: url(/skin/jobyhome/img/right_swt/f-ico3.png) no-repeat center;background-size: 30px 30px}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-youtube:hover{background: url(/skin/jobyhome/img/right_swt/f-ico3-3.png) #009b4c no-repeat center;background-size: 30px 30px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-twitter{background: url(/skin/jobyhome/img/right_swt/f-ico4.png) no-repeat center;background-size: 30px 30px;border-bottom: none;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-twitter:hover{background: url(/skin/jobyhome/img/right_swt/f-ico4-4.png) #009b4c no-repeat center;background-size: 30px 30px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li .msgbox{width: 110px;height: 40px;background: #009b4c;position: absolute;right: 50px;top: 7px;display: none;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li .msgbox:after{content: ''; width: 0;height: 0;border-style: solid;border-width: 5px 0 5px 10px; right: -8px;top: 15px;position: absolute; border-color: transparent transparent transparent #009b4c;line-height: 0px;_border-color: #000000 #000000 #000000 #009b4c;_filter: progid:DXImageTransform.Microsoft.Chroma(color='#000000');}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li .msgbox p{color: #FFFFFF;line-height: 40px;font-size: 14px;text-align: left;text-indent: 34px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li:hover .msgbox{display: block; animation:myswt 0.5s alternate;-webkit-animation:myswt 0.5s  alternate;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-facebook .msgbox{background: url(/skin/jobyhome/img/right_swt/f-ico1-1.png) #009b4c no-repeat center;background-size: 20px 20px;background-position-x: 6px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-linkedin .msgbox{background: url(/skin/jobyhome/img/right_swt/f-ico2-2.png) #009b4c no-repeat center;background-size: 20px 20px;background-position-x: 6px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-youtube .msgbox{background: url(/skin/jobyhome/img/right_swt/f-ico3-3.png) #009b4c no-repeat center;background-size: 20px 20px;background-position-x: 6px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-twitter .msgbox{background: url(/skin/jobyhome/img/right_swt/f-ico4-4.png) #009b4c no-repeat center;background-size: 20px 20px;background-position-x: 6px;}");
document.writeln("	.right_swt_pc .right_swt_pc_tab ul li.f-whatsapp .msgbox{background: url(/skin/jobyhome/img/right_swt/f-ico6-6.png) #009b4c no-repeat center;background-size: 20px 20px;background-position-x: 6px;}");
document.writeln("	");
document.writeln("	.right_swt_wap{width: 100%;box-sizing: border-box;padding: 0 4%;overflow: hidden;background: #FFFFFF;position: fixed;bottom: 0;display: none;z-index:999999;}");
document.writeln("	.right_swt_wap .f-swt{overflow: hidden;box-sizing: border-box;padding: 0.5rem 0;}");
document.writeln("	.right_swt_wap .f-swt ul li{width: 46.5625%;height: 5rem;font-size: 2rem;}");
document.writeln("	.right_swt_wap .f-swt ul li:first-child{float: left;background: url(/skin/jobyhome/img/right_swt/f-ico_chat.png) #1ab3ff no-repeat center;background-size: 3rem 3rem;background-position-x: 1.5rem; text-indent: 4rem;}");
document.writeln("	.right_swt_wap .f-swt ul li:last-child{float: right;background: url(/skin/jobyhome/img/right_swt/f-ico_tel.png) #071bc9 no-repeat center;background-size: 3rem 3rem;background-position-x: 2rem;text-indent: 5rem;}");
document.writeln("	.right_swt_wap .f-swt ul li a{color: #FFFFFF;text-align: center;display: block;line-height: 5rem;}");
document.writeln("	");
document.writeln("	@media (max-width: 640px) {.right_swt_pc{display: none;}.right_swt_wap{display: block;}}");
document.writeln("	@keyframes myswt{from {right: 60px;}to {right: 50px;}}");
document.writeln("	@-webkit-keyframes myswt{from {right: 60px;}to {right: 50px;}}");
document.writeln("</style>");
			
			
document.getElementById("whatsapp_pc").href = 'https://api.whatsapp.com/send?phone=8618151000009&text=Hi, JOBY, How are you? I am pretty interested in your products, could i know more about your products.'+location.href+'&data&lang=en';
document.getElementById("whatsapp_wap").href = 'https://api.whatsapp.com/send?phone=8618151000009&text=Hi, JOBY, How are you? I am pretty interested in your products, could i know more about your products.'+location.href+'&data&lang=en';
